apiVersion: v1
data:
  index.html: "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"UTF-8\">\n<title>PRODUCTION
    ENVIRONMENT</title>\n</head>\n<body>\n\n<h1> \U0001F525 Application Deployed on
    PRODUCTION Environment</h1>\n\n<p style=\"margin-top:30px;\">\n    This is a Prod
    environment.\n</p>\n\n</body>\n</html>"
kind: ConfigMap
metadata:
  name: kargo-demo-content
