apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>UAT ENVIRONMENT</title>
    </head>
    <body>

    <h1>🚀 Application Deployed on UAT Environment</h1>

    <p style="margin-top:30px;">
        This is a UAT Acceptance environment.
    </p>

    </body>
    </html>
